# Generated by Django 6.0.6 on 2026-06-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude of the complaint location')),
                ('longitude', models.FloatField(help_text='Longitude of the complaint location')),
                ('description', models.TextField(blank=True, help_text='Description of the issue')),
                ('category', models.CharField(choices=[('potholes', 'Potholes / Road Damage'), ('streetlight', 'Broken Streetlight'), ('graffiti', 'Graffiti / Vandalism'), ('illegal_dumping', 'Illegal Dumping'), ('sidewalk', 'Damaged Sidewalk'), ('traffic', 'Traffic Sign / Signal Issue'), ('noise', 'Noise Complaint'), ('park', 'Park / Public Space Issue'), ('water', 'Water / Drainage Issue'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('hidden', 'Hidden'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Optional photo of the issue', null=True, upload_to='complaint_photos/')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Submitter's IP (for rate limiting / abuse tracking)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='complaints__status_f077e8_idx'), models.Index(fields=['latitude', 'longitude'], name='complaints__latitud_7c96e8_idx')],
            },
        ),
    ]
