# Generated by Django 6.0.6 on 2026-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='custom_category',
            field=models.CharField(blank=True, default='', help_text="User-defined category name when category is 'other'", max_length=100),
        ),
    ]
