# Generated by Django 6.0.6 on 2026-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_custom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='action_requested',
            field=models.TextField(blank=True, default='', help_text='What action would you like to be taken?'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='impact',
            field=models.TextField(blank=True, default='', help_text='How does this issue affect you or the community?'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the issue (Situation)'),
        ),
    ]
