# Generated by Django 6.0.6 on 2026-06-19 11:49

from django.db import migrations, models


def convert_hidden_to_pending(apps, schema_editor):
    Complaint = apps.get_model('complaints', 'Complaint')
    Complaint.objects.filter(status='hidden').update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_action_requested_complaint_impact_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_hidden_to_pending, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20),
        ),
    ]
