# Generated by Django 6.0.6 on 2026-06-22 04:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_acknowledged_at_complaint_official_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'mp4', 'webm', 'mov', 'mp3', 'wav', 'ogg', 'm4a'])])),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ReportScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, help_text='Overall score 0-100')),
                ('letter_grade', models.CharField(default='F', max_length=1)),
                ('specificity', models.IntegerField(default=0, help_text='Locations, measurements, landmarks (0-30)')),
                ('context', models.IntegerField(default=0, help_text='Time, frequency, affected people (0-25)')),
                ('clarity', models.IntegerField(default=0, help_text='Well-structured description (0-20)')),
                ('completeness', models.IntegerField(default=0, help_text='Photo, impact, action requested (0-15)')),
                ('actionability', models.IntegerField(default=0, help_text='Suggested action (0-10)')),
                ('description_detail', models.TextField(blank=True, default='', help_text='Analysis notes explaining the score breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
