# Generated by Django 6.0.6 on 2026-06-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportscore',
            name='clarity',
            field=models.IntegerField(default=0, help_text='Coherence: tells a complete story (0-20)'),
        ),
        migrations.AlterField(
            model_name='reportscore',
            name='context',
            field=models.IntegerField(default=0, help_text='Detail quality: location, time, people, sensory signals (0-30)'),
        ),
        migrations.AlterField(
            model_name='reportscore',
            name='specificity',
            field=models.IntegerField(default=0, help_text='Structure: situation/impact/action fields filled (0-25)'),
        ),
    ]
