# Generated by Django 6.0.6 on 2026-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('potholes', 'Roads'), ('streetlight', 'Lighting'), ('graffiti', 'Vandalism'), ('illegal_dumping', 'Garbage'), ('sidewalk', 'Walkways'), ('traffic', 'Traffic'), ('noise', 'Noise'), ('park', 'Public Space'), ('water', 'Flooding'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
    ]
